### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by jagduarte**
Hi, can I add a license file to the Propy? I am a Bioinformatician student and I used your package  to develop a tool in my master thesis in the area of machine learning. This tool has to be stored in the Galaxy platfrom, but in order to do this all que packages must exist in conda. I took the liberty to add propy to conda (I hope you dont mind) but in order to do this they require a license file, like LGPL. Can you add this lincense file so they can upload the package to conda and I can finish my thesis? 

Thank you very much

### CODE REVIEW

**Comment by jagduarte** [comment]
@MartinThoma @MarinaParr  @jowch @ArchieV1

**Comment by MartinThoma** [comment]
The reason why I'm hesitant on this is the fact that I'm not the original author. I would need to look up the original license. If there is none, then you need to ask the original authors.

**Comment by jhahnfeld** [comment]
Hi, I am also interested in using propy3 for my work and the addition of a license would be much appreciated.

The original [website](https://code.google.com/archive/p/protpy/) of propy/protpy states the license as [GNU GPL v2 or later](https://www.gnu.org/licenses/old-licenses/gpl-2.0.html) and according to the license compatibility [list](https://www.gnu.org/licenses/gpl-faq.html#AllCompatibility) you can use the GPLv3 license.

Thanks again and best regards!

Julian

**Comment by MartinThoma** [comment]
Looking at your compatibility list, I don't think that I can simply put it under GPLv3. It was originally under GPLv2 (only).

image

**Comment by MartinThoma** [comment]
Ah, sorry, you meant LGPLv3 :thinking:

**Comment by MartinThoma** [comment]
If anybody knows how to reach Dongsheng Cao and Yizeng Liang to clarify this, please let me know. I'm happy to help you with maintaining this software, but I don't want to get into legal issues.

**Comment by jhahnfeld** [comment]
I can only find the license type "GPL" without a version number in the original source code. The linked GPLv2 license text on the website contains the clause "or later" in paragraph 9.

If it was originally licensed as GPLv2 only we could also use a GPLv2 only license.

Have you tried Yizeng Liang's mail address [yizeng_liang@263.net](mailto:yizeng_liang@263.net) from the original [publication](https://academic.oup.com/bioinformatics/article/29/7/960/253928?login=false)?

**Comment by MartinThoma** [comment]
> Have you tried Yizeng Liang's mail address [yizeng_liang@263.net](mailto:yizeng_liang@263.net) from the original [publication](https://academic.oup.com/bioinformatics/article/29/7/960/253928?login=false)?

Yes. The mailserver replies:

> 550 yizeng_liang@263.net:user locked (in reply to RCPT TO command)

**Comment by jhahnfeld** [comment]
I have found the mail address of Dong-Sheng Cao: [oriental-cds@163.com](mailto:oriental-cds@163.com)
This one should still be active.

**Comment by MartinThoma** [comment]
I've tried that one already a couple of times. No response.

I will look into the original license this weekend. If I find it, I would just take the same license here. Would that help you?

**Comment by jhahnfeld** [comment]
> I've tried that one already a couple of times. No response.

Thank you very much for your efforts.

> I will look into the original license this weekend. If I find it, I would just take the same license here. Would that help you?

Yes, that would help me a lot.

**Comment by MartinThoma** [comment]
One other question I need to clarify in this context is whom to mention in which way in the "author" field: https://opensource.stackexchange.com/q/12675/3618

**Comment by MartinThoma** [comment]
@jhahnfeld @josegduarte I think the following should be legally correct: https://github.com/MartinThoma/propy3/pull/15/commits

I'll close this PR as #15 replaces it. Please leave any ideas / concerns you have there. On Sunday afternoon (tomorrow), I'll merge it + make a patch release of propy 3.

**Pull request closed without merging**
